version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    env_file: ".env"
    environment:
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_AUTH_DOMAIN=${VITE_AUTH_DOMAIN}
      - VITE_PROJECT_ID=${VITE_PROJECT_ID}
      - VITE_STORAGE_BUCKET=${VITE_STORAGE_BUCKET}
      - VITE_MESSAGING_SENDER_ID=${VITE_MESSAGING_SENDER_ID}
      - VITE_APP_ID=${VITE_APP_ID}

    container_name: portfolio
